documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "docs/**"
          - "**/*.md"

enhancement:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.tf"
          - "templates/**"
          - "examples/**"
          - "tests/**"
          - ".github/workflows/**"
