name: Feature request
description: Suggest an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Please share the details below.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / use case
      description: Why is this valuable? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, diagrams, or references.
