'use client';

import { useState, useEffect } from 'react';

type TfvarsInput = {
  project_id: string;
  region: string;
  zone: string;
  wg_port: number;
  wgeasy_ui_port: number;
  ui_source_ranges: string;
  ssh_source_ranges: string;
  openclaw_gateway_port: number;
  openclaw_enable_public_ip: boolean;
  openclaw_version: string;
};

const defaultInput: TfvarsInput = {
  project_id: '',
  region: 'asia-northeast3',
  zone: 'asia-northeast3-a',
  wg_port: 51820,
  wgeasy_ui_port: 51821,
  ui_source_ranges: '0.0.0.0/0',
  ssh_source_ranges: '0.0.0.0/0',
  openclaw_gateway_port: 8080,
  openclaw_enable_public_ip: false,
  openclaw_version: 'latest',
};

export default function WizardPage() {
  const [input, setInput] = useState<TfvarsInput>(defaultInput);
  const [tfvars, setTfvars] = useState('');

  useEffect(() => {
    localStorage.setItem('ops-console-input', JSON.stringify(input));

    const generateTfvars = () => {
      let content = '# Generated by Ops Console\n\n';
      content += `project_id = "${input.project_id}"\n`;
      content += `region     = "${input.region}"\n`;
      content += `zone       = "${input.zone}"\n\n`;
      
      content += `wg_port           = ${input.wg_port}\n`;
      content += `wgeasy_ui_port    = ${input.wgeasy_ui_port}\n`;
      content += `ui_source_ranges  = ["${input.ui_source_ranges}"]\n`;
      content += `ssh_source_ranges = ["${input.ssh_source_ranges}"]\n\n`;
      
      content += `openclaw_gateway_port      = ${input.openclaw_gateway_port}\n`;
      content += `openclaw_enable_public_ip  = ${input.openclaw_enable_public_ip}\n`;
      content += `openclaw_version           = "${input.openclaw_version}"\n`;
      
      setTfvars(content);
    };

    generateTfvars();
  }, [input]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;
    const val = type === 'checkbox' ? (e.target as HTMLInputElement).checked : 
                type === 'number' ? parseInt(value) : value;
    
    setInput(prev => ({ ...prev, [name]: val }));
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(tfvars);
    alert('Copied to clipboard!');
  };

  return (
    <div className="container">
      <header style={{ marginBottom: '2rem' }}>
        <h2 style={{ fontSize: '1.75rem', fontWeight: 'bold' }}>Deploy Wizard</h2>
        <p style={{ color: 'var(--text-muted)' }}>Configure your GCP infrastructure variables.</p>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <section className="card">
            <h3 style={{ fontSize: '1rem', fontWeight: '600', marginBottom: '1rem' }}>GCP Basics</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>Project ID</label>
                <input 
                  style={{ width: '100%' }}
                  name="project_id"
                  value={input.project_id}
                  onChange={handleChange}
                  placeholder="my-gcp-project-id"
                />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>Region</label>
                  <input name="region" value={input.region} onChange={handleChange} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>Zone</label>
                  <input name="zone" value={input.zone} onChange={handleChange} />
                </div>
              </div>
            </div>
          </section>

          <section className="card">
            <h3 style={{ fontSize: '1rem', fontWeight: '600', marginBottom: '1rem' }}>WireGuard (VPN)</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>WG Port (UDP)</label>
                  <input type="number" name="wg_port" value={input.wg_port} onChange={handleChange} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>UI Port (TCP)</label>
                  <input type="number" name="wgeasy_ui_port" value={input.wgeasy_ui_port} onChange={handleChange} />
                </div>
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>SSH Source Ranges</label>
                <input style={{ width: '100%' }} name="ssh_source_ranges" value={input.ssh_source_ranges} onChange={handleChange} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>UI Source Ranges</label>
                <input style={{ width: '100%' }} name="ui_source_ranges" value={input.ui_source_ranges} onChange={handleChange} />
              </div>
            </div>
          </section>

          <section className="card">
            <h3 style={{ fontSize: '1rem', fontWeight: '600', marginBottom: '1rem' }}>OpenClaw</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>Gateway Port</label>
                  <input type="number" name="openclaw_gateway_port" value={input.openclaw_gateway_port} onChange={handleChange} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '0.85rem', marginBottom: '0.4rem' }}>Version</label>
                  <input name="openclaw_version" value={input.openclaw_version} onChange={handleChange} />
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <input 
                  type="checkbox" 
                  id="enable_public" 
                  name="openclaw_enable_public_ip" 
                  checked={input.openclaw_enable_public_ip} 
                  onChange={handleChange}
                />
                <label htmlFor="enable_public" style={{ fontSize: '0.85rem' }}>Enable Public IP (Not recommended for production)</label>
              </div>
            </div>
          </section>
        </div>

        <div>
          <section className="card" style={{ position: 'sticky', top: '2rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
              <h3 style={{ fontSize: '1rem', fontWeight: '600' }}>terraform.tfvars Preview</h3>
              <button onClick={copyToClipboard} className="btn btn-outline" style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}>
                Copy
              </button>
            </div>
            <pre style={{ 
              background: 'var(--accent)', 
              padding: '1rem', 
              borderRadius: '0.375rem', 
              fontSize: '0.85rem',
              color: 'var(--primary)',
              overflowX: 'auto',
              minHeight: '400px',
              border: '1px solid var(--border)'
            }}>
              {tfvars}
            </pre>
            <p style={{ marginTop: '1rem', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              Copy this content into a file named <code>terraform.tfvars</code> under <code>infra/</code> (for example <code>infra/terraform.tfvars</code>).
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
